services:
  postgres:
    image: 'postgres:17-alpine'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
      - 'PGUSER=myuser'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d mydatabase" ]
      interval: 2s
      timeout: 2s
      retries: 3

  application:
    image: 'xogame:latest'
    environment:
      spring.datasource.url: 'jdbc:postgresql://postgres:5432/mydatabase'
      spring.datasource.username: 'myuser'
      spring.datasource.password: 'secret'
      THC_PATH: /actuator/health
      THC_PORT: 8080
    ports:
      - "8080:8080"
    links:
      - postgres
    healthcheck:
      test: [ "CMD", "/workspace/health-check" ]
      interval: 1s
      timeout: 1s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
